FROM node:19-alpine3.16 AS build

COPY frontend/chatapp/ /chatapp
WORKDIR /chatapp

RUN npm run build

FROM nginx:1.23.4

COPY --from=build /chatapp/build /var/www
COPY /frontend/nginx.conf /etc/nginx

WORKDIR /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
