version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8081:3000"
    command: /bin/sh -c "while sleep 1000; do :; done"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - "8080:8080"
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: mysql:8.0
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "3306:3306"
